// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/gopython/gopython.proto

package gopython

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoPythonClient is the client API for GoPython service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoPythonClient interface {
	SetBatchSize(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error)
}

type goPythonClient struct {
	cc grpc.ClientConnInterface
}

func NewGoPythonClient(cc grpc.ClientConnInterface) GoPythonClient {
	return &goPythonClient{cc}
}

func (c *goPythonClient) SetBatchSize(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, "/gopython.GoPython/SetBatchSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoPythonServer is the server API for GoPython service.
// All implementations must embed UnimplementedGoPythonServer
// for forward compatibility
type GoPythonServer interface {
	SetBatchSize(context.Context, *BatchRequest) (*BatchResponse, error)
	mustEmbedUnimplementedGoPythonServer()
}

// UnimplementedGoPythonServer must be embedded to have forward compatible implementations.
type UnimplementedGoPythonServer struct {
}

func (UnimplementedGoPythonServer) SetBatchSize(context.Context, *BatchRequest) (*BatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBatchSize not implemented")
}
func (UnimplementedGoPythonServer) mustEmbedUnimplementedGoPythonServer() {}

// UnsafeGoPythonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoPythonServer will
// result in compilation errors.
type UnsafeGoPythonServer interface {
	mustEmbedUnimplementedGoPythonServer()
}

func RegisterGoPythonServer(s grpc.ServiceRegistrar, srv GoPythonServer) {
	s.RegisterService(&GoPython_ServiceDesc, srv)
}

func _GoPython_SetBatchSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPythonServer).SetBatchSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopython.GoPython/SetBatchSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPythonServer).SetBatchSize(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoPython_ServiceDesc is the grpc.ServiceDesc for GoPython service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoPython_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gopython.GoPython",
	HandlerType: (*GoPythonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetBatchSize",
			Handler:    _GoPython_SetBatchSize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gopython/gopython.proto",
}
