// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: proto/gopython/gopython.proto

package gopython

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoPythonClient is the client API for GoPython service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoPythonClient interface {
	InitializeModel(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	ModelInference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error)
	RemoveModel(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
}

type goPythonClient struct {
	cc grpc.ClientConnInterface
}

func NewGoPythonClient(cc grpc.ClientConnInterface) GoPythonClient {
	return &goPythonClient{cc}
}

func (c *goPythonClient) InitializeModel(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, "/gopython.GoPython/InitializeModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goPythonClient) ModelInference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error) {
	out := new(InferenceResponse)
	err := c.cc.Invoke(ctx, "/gopython.GoPython/ModelInference", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goPythonClient) RemoveModel(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, "/gopython.GoPython/RemoveModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoPythonServer is the server API for GoPython service.
// All implementations must embed UnimplementedGoPythonServer
// for forward compatibility
type GoPythonServer interface {
	InitializeModel(context.Context, *InitializeRequest) (*InitializeResponse, error)
	ModelInference(context.Context, *InferenceRequest) (*InferenceResponse, error)
	RemoveModel(context.Context, *RemoveRequest) (*RemoveResponse, error)
	mustEmbedUnimplementedGoPythonServer()
}

// UnimplementedGoPythonServer must be embedded to have forward compatible implementations.
type UnimplementedGoPythonServer struct {
}

func (UnimplementedGoPythonServer) InitializeModel(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitializeModel not implemented")
}
func (UnimplementedGoPythonServer) ModelInference(context.Context, *InferenceRequest) (*InferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModelInference not implemented")
}
func (UnimplementedGoPythonServer) RemoveModel(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveModel not implemented")
}
func (UnimplementedGoPythonServer) mustEmbedUnimplementedGoPythonServer() {}

// UnsafeGoPythonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoPythonServer will
// result in compilation errors.
type UnsafeGoPythonServer interface {
	mustEmbedUnimplementedGoPythonServer()
}

func RegisterGoPythonServer(s grpc.ServiceRegistrar, srv GoPythonServer) {
	s.RegisterService(&GoPython_ServiceDesc, srv)
}

func _GoPython_InitializeModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPythonServer).InitializeModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopython.GoPython/InitializeModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPythonServer).InitializeModel(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoPython_ModelInference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPythonServer).ModelInference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopython.GoPython/ModelInference",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPythonServer).ModelInference(ctx, req.(*InferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoPython_RemoveModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoPythonServer).RemoveModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gopython.GoPython/RemoveModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoPythonServer).RemoveModel(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoPython_ServiceDesc is the grpc.ServiceDesc for GoPython service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoPython_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gopython.GoPython",
	HandlerType: (*GoPythonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitializeModel",
			Handler:    _GoPython_InitializeModel_Handler,
		},
		{
			MethodName: "ModelInference",
			Handler:    _GoPython_ModelInference_Handler,
		},
		{
			MethodName: "RemoveModel",
			Handler:    _GoPython_RemoveModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gopython/gopython.proto",
}
