# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gopython.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egopython.proto\x12\x08gopython\"\"\n\x0c\x42\x61tchRequest\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\"\x1f\n\rBatchResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2M\n\x08GoPython\x12\x41\n\x0cSetBatchSize\x12\x16.gopython.BatchRequest\x1a\x17.gopython.BatchResponse\"\x00\x42\x19Z\x17\x63s425mp3/proto/gopythonb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gopython_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\027cs425mp3/proto/gopython'
  _BATCHREQUEST._serialized_start=28
  _BATCHREQUEST._serialized_end=62
  _BATCHRESPONSE._serialized_start=64
  _BATCHRESPONSE._serialized_end=95
  _GOPYTHON._serialized_start=97
  _GOPYTHON._serialized_end=174
# @@protoc_insertion_point(module_scope)
